// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230517154743_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SharedResources.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "ca093598-43aa-4f56-94b4-d60d73b41769",
                            Description = "Description for product 1",
                            ImageUrl = "https://picsum.photos/seed/1/200/300",
                            Name = "Product 1",
                            Price = 10m
                        },
                        new
                        {
                            Id = "0075fa58-9e6c-426f-a06a-7dfccfee75f7",
                            Description = "Description for product 2",
                            ImageUrl = "https://picsum.photos/seed/2/200/300",
                            Name = "Product 2",
                            Price = 20m
                        },
                        new
                        {
                            Id = "6d8431a7-7fae-4195-b767-4349422a3ca9",
                            Description = "Description for product 3",
                            ImageUrl = "https://picsum.photos/seed/3/200/300",
                            Name = "Product 3",
                            Price = 30m
                        },
                        new
                        {
                            Id = "493ff633-24a4-4604-b3c8-c37b13ebcad5",
                            Description = "Description for product 4",
                            ImageUrl = "https://picsum.photos/seed/4/200/300",
                            Name = "Product 4",
                            Price = 40m
                        },
                        new
                        {
                            Id = "7071b9cd-7119-4572-ad9b-a85f173e9c7d",
                            Description = "Description for product 5",
                            ImageUrl = "https://picsum.photos/seed/5/200/300",
                            Name = "Product 5",
                            Price = 50m
                        },
                        new
                        {
                            Id = "a327435a-ba66-43c0-852a-6e19761203fd",
                            Description = "Description for product 6",
                            ImageUrl = "https://picsum.photos/seed/6/200/300",
                            Name = "Product 6",
                            Price = 60m
                        },
                        new
                        {
                            Id = "c1d1fc84-23a6-434f-9cbd-e72c31ec9063",
                            Description = "Description for product 7",
                            ImageUrl = "https://picsum.photos/seed/7/200/300",
                            Name = "Product 7",
                            Price = 70m
                        },
                        new
                        {
                            Id = "985b8626-b1f8-4279-b0ab-646719e99145",
                            Description = "Description for product 8",
                            ImageUrl = "https://picsum.photos/seed/8/200/300",
                            Name = "Product 8",
                            Price = 80m
                        },
                        new
                        {
                            Id = "bd4cba41-2f7b-4d62-b868-19adf2c9c586",
                            Description = "Description for product 9",
                            ImageUrl = "https://picsum.photos/seed/9/200/300",
                            Name = "Product 9",
                            Price = 90m
                        },
                        new
                        {
                            Id = "0d4b434b-9a72-41e0-b86a-6d3fc4538890",
                            Description = "Description for product 10",
                            ImageUrl = "https://picsum.photos/seed/10/200/300",
                            Name = "Product 10",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
