// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SharedResources.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "444831a2-b45c-4329-9995-dd646d8b4bf9",
                            Description = "Description for product 1",
                            ImageUrl = "https://picsum.photos/seed/1/200/300",
                            Name = "Product 1",
                            Price = 10L
                        },
                        new
                        {
                            Id = "e1156c28-92ef-4e4f-b56e-ae79bed24952",
                            Description = "Description for product 2",
                            ImageUrl = "https://picsum.photos/seed/2/200/300",
                            Name = "Product 2",
                            Price = 20L
                        },
                        new
                        {
                            Id = "09a9bb7a-5c5a-499e-8b1f-303449e86f44",
                            Description = "Description for product 3",
                            ImageUrl = "https://picsum.photos/seed/3/200/300",
                            Name = "Product 3",
                            Price = 30L
                        },
                        new
                        {
                            Id = "402fbb85-3461-4e67-bdd6-bcef2b5766a2",
                            Description = "Description for product 4",
                            ImageUrl = "https://picsum.photos/seed/4/200/300",
                            Name = "Product 4",
                            Price = 40L
                        },
                        new
                        {
                            Id = "5bd416be-f365-438a-8ffa-4ecd37b07ba7",
                            Description = "Description for product 5",
                            ImageUrl = "https://picsum.photos/seed/5/200/300",
                            Name = "Product 5",
                            Price = 50L
                        },
                        new
                        {
                            Id = "7e503df6-9e02-49a2-91ed-e5609f3e4b60",
                            Description = "Description for product 6",
                            ImageUrl = "https://picsum.photos/seed/6/200/300",
                            Name = "Product 6",
                            Price = 60L
                        },
                        new
                        {
                            Id = "4fba4918-9e8b-47ff-bcc4-4a10792c0008",
                            Description = "Description for product 7",
                            ImageUrl = "https://picsum.photos/seed/7/200/300",
                            Name = "Product 7",
                            Price = 70L
                        },
                        new
                        {
                            Id = "8c817c45-95fd-410d-92b4-5ad162df0aa4",
                            Description = "Description for product 8",
                            ImageUrl = "https://picsum.photos/seed/8/200/300",
                            Name = "Product 8",
                            Price = 80L
                        },
                        new
                        {
                            Id = "2de2864d-4cc4-48d0-b21d-89bbac5ab2a6",
                            Description = "Description for product 9",
                            ImageUrl = "https://picsum.photos/seed/9/200/300",
                            Name = "Product 9",
                            Price = 90L
                        },
                        new
                        {
                            Id = "c82586ad-ae90-4885-a3ae-3713cf95bb2c",
                            Description = "Description for product 10",
                            ImageUrl = "https://picsum.photos/seed/10/200/300",
                            Name = "Product 10",
                            Price = 100L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
